# Base configs
baseurl: "http://3000pixels.gihtub.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-114898267-1"

# UI configs
title: "Photography"
subtitle: "Ver o que vista alcança através da lente"
author: "José Manuel"
header:
 title: "Photography"
 subtitle: "by José Manuel "
footer:
 name: "Hey there, my name is José Manuel"
 bio: "I am photographer amateur and I love photography "
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com//mistermoonblood"
  twitter: "https://www.twitter.com//mistermoonblood666@hotmail.com"
  instagram: "https://www.instagram.com/the_crow_flies_during_a_storm"
  dribbble: 
  linkedin: 
  github: 
